educational_heritage/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^repository/', include('repository.urls')),
    url(r'^landing/', include('landing.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^account/profile/', TemplateView.as_view(template_name='account/profile.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
]

landing/urls.py
"""Landing urls."""

from django.conf.urls import url

from . import views

app_name = 'landing'

urlpatterns = [
    # /landing/
    url(r'^$', views.index, name='index'),
    # /landing/subscribe/
    url(r'^subscribe/$', views.subscribe, name='subscribe'),
    # /landing/3f9895b9-1ad8-4b63-bac3-45225d585502/
    url(r'^(?P<subscriber_uuid>[0-9a-z-]+)/$', views.thanks, name='thanks'),
]

repository/urls.py
"""Repository urls."""

from django.conf.urls import url

from . import views

app_name = 'repository'

urlpatterns = [
    # /repository/
    url(r'^$', views.index, name='index'),
]

account/models.py
"""Account models."""

import hashlib

from allauth.account.models import EmailAddress
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    """UserProfile model."""

    user = models.OneToOneField(User, related_name='profile')

    def __unicode__(self):
        """Render a string representation."""
        return "{}'s profile".format(self.user.username)

    class Meta:
        """Model metadata."""

        db_table = 'user_profile'

    def account_verified(self):
        """Detect the user’s email-verification status."""
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False

    def profile_image_url(self):
        """Display the user's gravatar icon."""
        return "http://www.gravatar.com/avatar/{}?s=40".format(hashlib.md5(self.user.email.encode('utf-8')).hexdigest())

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

landing/models.py
"""Landing models."""
from __future__ import unicode_literals

import uuid

from django.db import models


class Subscriber(models.Model):
    """Subscriber model."""

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return email."""
        return self.email

repository/models.py
"""Repository model."""

from django.db import models


class Item(models.Model):
    """Item model."""

    title = models.TextField(default='')
    description = models.TextField(default='')
    image = models.TextField(default='')
    url = models.TextField(default='')

landing/forms.py
"""Landing forms."""

from django import forms


class SubscriberForm(forms.Form):
    """Subscriber form."""

    email = forms.EmailField(
        label='',
        max_length=254,
        widget=forms.EmailInput(attrs={'class': "form-control input-lg",
                                       'placeholder': "nombre@dominio.com"}),
    )

account/views.py
"""Account views."""

# from django.shortcuts import render

# Create your views here.

landing/views.py
"""Landing views."""

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .forms import SubscriberForm
from .models import Subscriber


def index(request):
    """Home page."""
    form = SubscriberForm()
    return render(request, 'landing/index.html', {'form': form})


def thanks(request, subscriber_uuid):
    """Subscribed page."""
    subscriber = get_object_or_404(Subscriber, pk=subscriber_uuid)
    context = {'subscriber': subscriber}
    return render(request, 'landing/thanks.html', context)


def subscribe(request):
    """Subscribe page."""
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            subscriber, created = Subscriber.objects.get_or_create(
                email=form.cleaned_data['email'])
            return HttpResponseRedirect(reverse('landing:thanks', kwargs={'subscriber_uuid': subscriber.uuid}))

        return render(request, 'landing/index.html', {'form': form})

    return HttpResponseRedirect(reverse('landing:index'))

repository/views.py
"""repository app views."""

from django.shortcuts import render

from repository.models import Item


def index(request):
    """Home page view."""
    items = Item.objects.all()
    return render(request, 'repository/index.html', {'items': items})

landing/templates/landing/index.html
{% extends "base.html" %} 
{% load bootstrap3 %}
{% block content %}
    <div class="jumbotron">
      <div class="row">
        <div class="col-md-8">
          <h1>Personas mejorando la educación</h1>
          <p class="lead">Crea recursos didacticos para la docencia de forma colaborativa y sencilla en minutos.</p>
        </div>
        <div class="col-md-4">
	  <form action="{% url 'landing:subscribe' %}" method="post">
	    {% csrf_token %}
	    {% bootstrap_form form %}
	    {% buttons %}
	    <button type="submit" class="btn btn-primary">Quiero crear mis propios recursos</button>
	    {% endbuttons %}
	  </form>
        </div>
      </div>
    </div> <!-- /jumbotron -->
    
    <div class="reinforcement-statement">
      <h3>Recursos libres para una educación libre</h3>
      <p>Un espacio único para crear recursos educativos libres de forma colaborativa. Podrás disponer de todo el material necesario para tus clases en cuestión de minutos. Distribuye el  material con total libertad, siempre. Tus alumnos te lo agradecerán.</p>
    </div>
    
    <div class="benefits">
      <div class="row">
        <div class="col-md-4 benefit">
	  <img src="/static/landing/png/benefit-1.png" />
          <h4>Para todo lo que constuyas</h4>
          <p>Aloja y administra todo el material. Puedes manterner tu trabajo en privado o compartirlo con el mundo.</p>
        </div>
        <div class="col-md-4 benefit">
	  <img src="/static/landing/png/benefit-2.png" />
          <h4>Una mejor manera de trabajar</h4>
          <p>Ayuda a los docentes simplificando la forma en la que crean y distribuyen su material.</p>
	</div>
        <div class="col-md-4 benefit">
	  <img src="/static/landing/png/benefit-3.png" />
          <h4>La mayor comunidad</h4>
          <p>Encontraras una gran cantidad de material. Utilizalo o inspirate para crear el tuyo propio.</p>
        </div>
      </div>
    </div>
    
    <div class="social-proof">
      <h3>¿Quién usa Recursos Educativos?</h3>
      <div class="row">
	<div class="proof col-md-4">
	<h4>Estudiantes</h4>
	<p>Crear tu propio material de apoyo en tus estudios. Mejora tu rendimiento escolar.</p>
	</div>
	<div class="proof col-md-4">
	<h4>Padres de Alumnos</h4>
	<p>Ayuda a tus hijos en su educación. Involucrate en la educación de tus hijos.</p>
	</div>
	<div class="proof col-md-4">
	<h4>Centros Educativos</h4>
	<p>Gestiona todo el material que necesitas en tus aulas. Promueve el intercambio transparente de recursos educativos.</p>
	</div>
      </div>
    </div>
{% endblock %} 

landing/templates/landing/thanks.html
{% extends "base.html" %}
{% block content %}
<div>
<p>Gracias por subscribirte {{ subscriber.email }}</p>
<p>En breve nos pondremos en contacto contigo y podrás empezar a crear tus propios materiales.</p>
{% endblock %}

repository/templates/repository/index.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}

<div class="page-header">
<h1>Recursos Educativos Abiertos</h1>
</div>


<div class="row">

{% for item in items %}

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/static/repository/png/{{ item.image }}">
      <div class="caption">
        <h3>{{ item.title }}</h3>
        <p>{{ item.description }}</p>
        <p><a href="/static/repository/pdf/{{ item.url }}" class="btn btn-primary" role="button">Lo quiero</a></p>
      </div>
    </div>
  </div>

{% endfor %}

</div> <!-- /row -->

{% endblock %}

templates/base.html
{% load bootstrap3 %}
{% load static %}
<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="description" content="Recursos Educativos Libres">
  <meta name="author" content="">
  <link rel="icon" href="{% static "landing/ico/favicon.ico" %}">

  <title>Recursos Educativos</title>

  <!-- Bootstrap core CSS -->
  {% bootstrap_css %}

  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <link href="{% static "landing/css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">

  <link rel="stylesheet" href="//cdn.jsdelivr.net/font-hack/2.020/css/hack.min.css">

  <!-- Custom styles for this template -->
  <link href="{% static "landing/css/landing.css" %}" rel="stylesheet">

  <script src="{% static "landing/js/ie-emulation-modes-warning.js" %}"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

  <nav class="navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Recursos Educativos</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="/repository">Explora</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
          <li><a href="/account/profile">
              {% if request.user.first_name or request.user.last_name %}
              {{ request.user.first_name }} {{ request.user.last_name }}
              {% else %}
              {{ request.user.username }}
              {% endif %}
          </a></li>
          <li><a id="logout" href="/accounts/logout"><span class="glyphicon glyphicon-log-out"></span> Salir</a></li>

          {% else %}
          <li><a id="dropbox_login" href="/accounts/dropbox_oauth2/login/"><span class="glyphicon glyphicon-log-in"></span> Entrar</a></li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

{% block content%}{% endblock%}

    <hr/>

    <footer>
      <p>Copyright &copy; 2016 Fundación Legado Educativo</p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "landing/js/jquery.min.js" %}"><\/script>')</script>
    {% bootstrap_javascript %}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "landing/js/ie10-viewport-bug-workaround.js" %}"></script>

</body>
</html>